#!/bin/bash

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Cloudflare Pages 수동 재배포 가이드"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "D1 바인딩을 추가하셨으니, 이제 재배포가 필요합니다."
echo ""
echo "📌 방법 1: Cloudflare Dashboard에서 재배포 (추천)"
echo "   1. https://dash.cloudflare.com/ 접속"
echo "   2. Workers & Pages → dagong 프로젝트 선택"
echo "   3. Deployments 탭 클릭"
echo "   4. 최신 배포 옆 '⋯' 메뉴 클릭"
echo "   5. 'Retry deployment' 선택"
echo "   6. 배포 완료 대기 (약 1-2분)"
echo ""
echo "📌 방법 2: CLI로 배포 (API 키 필요)"
echo "   1. Deploy 탭에서 Cloudflare API 키 설정"
echo "   2. 다음 명령어 실행:"
echo "      cd /home/user/webapp"
echo "      npm run deploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 현재 상태:"
echo "   - 빌드 완료: dist/ 디렉토리 준비됨"
echo "   - D1 바인딩: 추가 완료 (DB → webapp-production)"
echo "   - 다음 단계: 재배포 필요"
echo ""
echo "🔗 유용한 링크:"
echo "   - Cloudflare Dashboard: https://dash.cloudflare.com/"
echo "   - 프로젝트 URL: https://dagong-bi1.pages.dev/"
echo "   - D1 바인딩 가이드: /home/user/webapp/CLOUDFLARE_D1_BINDING_GUIDE.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
